GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Discord Ends Deal Talks With Microsoft",
    "author": "Sarah E. Needleman and Cara Lombardo",
    "url": "https://www.wsj.com/articles/discord-ends-deal-talks-with-microsoft-11618938806",
    "likes": 0
}